### ISSUE TITLE
Fix QR method

### ISSUE THREAD

**Issue by jirihnidek** [GeoMop/bapprox#16]
Make it possible to use QR method again.

**Comment by jirihnidek** [comment]
The program is terminated with this error:

```
Creating B matrix ...
Traceback (most recent call last):
  File "./src/main.py", line 51, in <module>
    main(parse_arguments())
  File "./src/main.py", line 29, in main
    terrain.approximate_terrain()
  File "/home/jiri/GitHub/bapprox/src/terrain_data.py", line 307, in approximate_terrain
    raw, diffs = approx.terrain.approx(solver_method, terrain, u_knots, v_knots, sparse=sparse)
  File "/home/jiri/GitHub/bapprox/src/approx/terrain.py", line 882, in approx
    return approx_qr(terrain_data, u_knots, v_knots, sparse)
  File "/home/jiri/GitHub/bapprox/src/approx/terrain.py", line 607, in approx_qr
    b_mat, interval = build_ls_matrix(u_knots, v_knots, terrain_data, True)
  File "/home/jiri/GitHub/bapprox/src/approx/terrain.py", line 239, in build_ls_matrix
    u_base_vec, i_idx = spline_base_vec(u_knots, terrain[idx, 0], 0, sparse)
  File "/home/jiri/GitHub/bapprox/src/approx/terrain.py", line 132, in spline_base_vec
    idx = find_index(knot_vec, t_param)
  File "/home/jiri/GitHub/bapprox/src/approx/terrain.py", line 105, in find_index
    if _t_param >= _knot_vec[est]:
IndexError: index -8207998 is out of bounds for axis 0 with size 15
```
